version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1
  cypress: cypress-io/cypress@3
commands:
  install:
    description: 'Install project dependencies'
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  lint:
    description: 'Check for code style and linting errors'
    steps:
      - run: npm run style
      - run: npm run lint
  build_and_test:
    description: 'Builds and tests Angular project'
    steps:
      - run: npx ng build --configuration production
      - attach_workspace:
          at: ~/
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
  store:
    description: 'Stores build_and_test artifacts'
    steps:
      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage
jobs:
  run_build_and_test:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/repo
    steps:
      - install
      - cypress/install
      - build_and_test
      - store
      - add_ssh_keys:
          fingerprints:
            - "e3:91:d1:b8:55:54:db:71:bc:44:07:a9:4a:6f:6f:ef"
workflows:
  build-and-test:
    jobs:
      - run_build_and_test
